; PlatformIO Project Configuration File

[platformio]
default_envs = adafruit_feather_rfm ; Default to RP2040 when hitting 'Build'

; --- RP2040 Feather Environment ---
[env:adafruit_feather_rfm]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather_rfm
framework = arduino
lib_deps =
    mikem/RadioHead @ ^1.120
    knolleary/PubSubClient @ ^2.8
    ; arduino-libraries/WiFiNINA @ ^1.8.14
; lib_ignore = WiFi ; Removed this so WiFiNINA can function

; --- M0 Feather Environment ---
[env:adafruit_feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
lib_deps =
    mikem/RadioHead @ ^1.120
    knolleary/PubSubClient @ ^2.8
    ; arduino-libraries/WiFiNINA @ ^1.8.14